version: '3.9'

services:
  node-red:
    image: nodered/node-red:latest-14
    restart: always
    environment:
      TZ: "${TIMEZONE}"
    volumes:
      - ${ROOT_PATH}/Data:/data
    networks:
      - node-red-net
      - smart-home-control

  nginx:
    build: ./Docker/nginx/Dockerfile
    links:
      - node-red
    environment:
      NGINX_PORT: "${NGINX_PORT}"
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
    command: /bin/sh -c "/run_nginx.sh"
    restart: always
    networks:
      - node-red-net
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
    name: "nginx-proxy"
  smart-home-control:
    external: true
    name: "smart-home-control"
  node-red-net:
    driver: bridge